---

- hosts: rpi
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
 
  - name: install fail2ban package
    apt:
      name: fail2ban
      state: latest
  
  - name: setup filter configuration file
    copy:
      dest: "/etc/fail2ban/filter.d/openvpn.local"
      content: |
        # Fail2Ban filter for selected OpenVPN rejections
        #
        #

        [Definition]

        # Example messages (other matched messages not seen in the testing server's logs):
        # Fri Sep 23 11:55:36 2016 TLS Error: incoming packet authentication failed from [AF_INET]59.90.146.160:51223
        # Thu Aug 25 09:36:02 2016 117.207.115.143:58922 TLS Error: TLS handshake failed

        failregex = ^ TLS Error: incoming packet authentication failed from \[AF_INET\]<HOST>:\d+$
                    ^ <HOST>:\d+ Connection reset, restarting
                    ^ <HOST>:\d+ TLS Auth Error
                    ^ <HOST>:\d+ TLS Error: TLS handshake failed$
                    ^ <HOST>:\d+ VERIFY ERROR

        ignoreregex = 
   
  - name: setup jail configuration file
    copy:
      dest: "/etc/fail2ban/jail.d/openvpn"
      content: |
        # Fail2Ban configuration fragment for OpenVPN

        [openvpn]
        enabled  = true
        port     = 1194
        protocol = udp
        filter   = openvpn
        logpath  = /var/log/openvpn.log
        maxretry = 3
        
  - name: Reload fail2ban service
    systemd:
      name: fail2ban
      state: reloaded
